[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mexal_pz"
version = "1.0.0"
authors = [
  { name="Nicolas Amadori", email="nicolas.amadori02@gmail.com" },
]